version: '3.8'

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: toilet-db
    environment:
      POSTGRES_DB: toilet_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"